print('dgjdshgalgndsgfdsgdfsg')
print('dgjdshgalgndsgfdsqwrgdfsg')
print('dgjdshgalgndsqeqgfdsgdfsg')
print('dgjdsh34galgndsgfdsgdfsg')
print('dgjdsh6galgndsgfdsgdfsg')
print('dgjdshga234lgndsgfdsgdfsg')
print('dgjdshg24algndsgfdsgdfsg')
print('dgjdshgalgndsgf765dsgdfsg')
