print('adjfbds,j')
print('asjdfnsdjfnaskdnfasfafsdfgsdfg')
print('asjdfnsdjfnaskdnfasfafsdqe1234123fgsdfg')
print('asjdfnsdjfnaskdnf23asfafsdfgsdfg')
print('asjdfnsdjfnaskdnfa23呃呃vsfafsdqe1234123fgsdfg')
